image: ertong/flutter:3.19.4-api34

variables:
  PUB_CACHE: ${CI_PROJECT_DIR}/.cache/.pub-cache
  GRADLE_USER_HOME: ${CI_PROJECT_DIR}/.cache/.gradle
  GEM_HOME: ${CI_PROJECT_DIR}/.cache/.gem
  GIT_STRATEGY: fetch
  GIT_DEPTH: "1"
  APP_BASENAME: stardebug

stages:
  - test
  - build
  - publish

before_script:
  - . ci-parse-tag.sh
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8

include:
  - local: _build/ci_android.yaml
  - local: _build/ci_ios.yaml
  - local: _build/ci_win32.yaml