name: star_debug
description: Starlink debug information parser
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.40+40

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: any
  logger: ^1.4.0
  path_provider: any
  drift: ^2.8.2
  sqlite3_flutter_libs: ^0.5.15
  i18n: any
  devicelocale: ^0.6.0
  permission_handler: ^10.3.0
  device_info_plus: ^9.0.2
  connectivity_plus: ^4.0.1
  json_annotation: ^4.8.1
  package_info_plus: ^4.0.2
  intl: any
  firebase_core: ^2.14.0
  firebase_crashlytics: any
  firebase_analytics: any
  clipboard: ^0.1.3
  time_machine: 0.9.17
  flutter_timezone: 1.0.6
  upgrader: ^7.1.0
  file_picker: any
  flex_list: 1.0.0
  grpc: 3.2.2
  protobuf: any
  fixnum: any
  dio: ^5.2.1
  syncfusion_flutter_charts: ^21.2.9
  recase: 4.1.0
  share_plus: ^7.0.2
  mutex: 3.0.1
  flutter_markdown: ^0.6.15
  url_launcher: 6.1.11
  flutter_email_sender: ^6.0.0
  convert: 3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  build_runner: any
  flutter_launcher_icons: any
  drift_dev: ^2.8.3

  # The lint set provided by the package is activated in the `analysis_options.yaml`
  flutter_lints: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "_misc/logo.png"
  image_path_android: "_misc/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "_misc/logo.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin
    - assets/images/
    - assets/images/devices/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
