name: star_debug
description: Starlink debug information parser
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+6

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: any
  shared_preferences: any
  logger: ^1.3.0
  path_provider: any
  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.15
  i18n: any
  devicelocale: ^0.6.0
  permission_handler: any
  device_info_plus: ^9.0.1
  connectivity_plus: ^4.0.1
  json_annotation: ^4.8.1
  package_info_plus: ^4.0.1
  intl: any
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.1
  firebase_analytics: any
  clipboard: ^0.1.3
  time_machine: 0.9.17
  flutter_native_timezone: 2.0.0
  upgrader: ^7.0.0
  file_picker: any
  gettext: 1.2.0
  gettext_parser: 0.2.0
  flex_list: 1.0.0
  grpc: 3.1.0
  dio: ^5.1.2
  syncfusion_flutter_charts: 21.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  build_runner: any
  flutter_launcher_icons: any

  # The lint set provided by the package is activated in the `analysis_options.yaml`
  flutter_lints: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "_misc/logo.png"
  image_path_android: "_misc/logo.png"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin
    - assets/images/
    - assets/images/devices/
    - assets/gettext/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
